--- # self configuration
server:
  port: 8762

spring:
  application:
    name: admin-server

--- # configuration for eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int} # needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
--- # management endpoints configuration
#TODO: For production you should carefully choose which endpoints to expose
management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints, adjust for production use
  endpoint:
    health:
      show-details: ALWAYS # Show detailed health information
    #TODO: change for WHEN_AUTHORIZED for production
    env:
      show-values: ALWAYS # Display environment variables with values
    configprops:
      show-values: ALWAYS # Display configuration properties with values
