spring:
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: http://localhost:8080
          predicates:
            - Path=/customer/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
